### ISSUE TITLE
The slug must be between 3 and 64 characters for Title and Slug

### ISSUE THREAD

**Issue by dynamiccontent** [wintercms/wn-blog-plugin#15]
Can we increase the number of allowed characters for Title and Slug? Right now it's so ridiculously low.

Are there any performance implications or penalties for having higher characters count for title and slug?

https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

I wish we would have at least 255 characters length or more if you go much higher than that it gets unusable because of SEO and so on.

Thank you.

**Comment by dynamiccontent** [comment]
Closing this. After checking in the tables of this plugin the columns are set to varchar at 191 characters so it's fine. I am still figuring out why it's not letting me import. It's possible I am doing something wrong as I am importing from october news plugin....

**Comment by bennothommo** [comment]
@dynamiccontent The category title and slug are limited to 64 characters. The blog post title and slug have no limits. The category should be a short name so that more importance is put to the blog title for SEO.
