### ISSUE TITLE
Blog title with a padlock when using custom API controller

### ISSUE THREAD

**Issue by AdrienAdB** [wintercms/wn-blog-plugin#44]
Post title starts with a padlock when using a custom controller.
https://github.com/wintercms/wn-blog-plugin/blob/main/models/Post.php#L412

Custom controller example:

```
return Post::
          isPublished()
          ->select('id', 'title', 'slug', 'excerpt', 'published_at')
          ->orderBy('published_at', 'desc')
          ->with('categories', 'featured_images')
          ->get();
```

Any possibility to disable this feature without extending the model?

**Comment by LukeTowers** [comment]
It looks like you might need to add `is_published` to your select statement, the `isPublished()` scope would apply that as a filter to avoid returning unpublished posts and then you wouldn't have any unpublished results (and thus any lock icons) in your results.

**Comment by AdrienAdB** [comment]
Thanks @LukeTowers 
Adding 'published' in select did the job.

```
$records = Post::
          isPublished()
          ->select('published', 'id', 'title', 'slug', 'excerpt', 'published_at')
          ->orderBy('published_at', 'desc')
          ->with('categories', 'featured_images')
          ->get();
```
