### ISSUE TITLE
Differences between blog menu in Winter.blog and Rainlab.blog relative to added plugins

### ISSUE THREAD

**Issue by jlongo** [wintercms/wn-blog-plugin#46]
I'm trying to migrate Rainlab.blog to Winter.blog. Not tested yet if the plugins are working without issues, but one aspect that jumps out are the blog menus. In rainlab.blog they are all integrated in one row, in Winter.blog they are splited with window split where it turns harder content edition. See images

Winter.blog migrated from Rainlab
![blog - winter after test migration](https://github.com/wintercms/wn-blog-plugin/assets/1572402/30b8a651-0304-40dd-bb56-17045eb60c3c)
Rainlab.blog
![blog - rainlab with plugins](https://github.com/wintercms/wn-blog-plugin/assets/1572402/4bb3fb46-57ca-46e9-b940-aa1022e23b87)
Winter.blog clean install with plugin taxonomy

![blog - winter clean install with plugin](https://github.com/wintercms/wn-blog-plugin/assets/1572402/b47b0b30-4616-4c62-b823-77260e9493bb)

TIA

JL

**Comment by jlongo** [comment]
It is possible to change the primary tabs of Winter.blog to the secondary tab. It is to me more clean than the primary tab style.
Where i can find any information how to change the tab used ?

TIA 
JL

Note: I'm trying to move all plugins to WinterCMS based plugins despite existing compatibility with October ones. I think i will do a fresh start trying to import all blog posts base and other content on a clean install... there is any plugin that can export/import ??? Not sure if JaxWiko.Migrator is up to the task but i will give it a try when i have time for that.

**Comment by LukeTowers** [comment]
@jlongo you don't have to import / export, if you just drop Winter.Blog in and delete the RainLab.Blog files and then run `artisan migrate` it will handle migrating for you through the [Plugin Replacement feature](https://wintercms.com/docs/v1.2/docs/plugin/replacement).

You might want to give the [Winter.TailwindUI](https://github.com/wintercms/wn-tailwindui-plugin) a try first before thinking that the secondary tabs are better for the blog plugin 😉

**Comment by LukeTowers** [comment]
But yes, @jaxwilko's migrator plugin should also handle migrating database table content for you if you want to, although it's not really meant for that and there really isn't a need to do that.

**Comment by jlongo** [comment]
Yes, i like the left menu of Winter.TailwindUI, but on blog i have the same problem... if i add plugins (in this case [GinoPane.BlogTaxonomy](https://packagist.org/packages/ginopane/wn-blogtaxonomy-plugin)) i get the window split with separated menus...  This is done on a clean install... So, the question remains... there is any any way to easily merge both menus and get a single window ?
![image](https://github.com/wintercms/wn-blog-plugin/assets/1572402/ecca71e2-752c-40b7-b75e-4bb57df01380)

**Comment by LukeTowers** [comment]
You should be able to do something like this:

```php
Event::listen('backend.form.extendFieldsBefore', function ((\Backend\Widgets\Form) $formWidget) {
    // Check that we're extending the correct Form widget instance
    if (
        !($formWidget->getController() instanceof \Winter\Blog\Controllers\Posts)
        || !($formWidget->model instanceof \Winter\Blog\Models\Post)
        || $formWidget->isNested
    ) {
        return;
    }

    $formWidget->tabs = array_merge($formWidget->tabs ?? [], $formWidget->secondaryTabs ?? []);
}, PHP_INT_MIN);
```
See https://wintercms.com/docs/v1.2/docs/events/introduction#subscribe-using-priority and https://wintercms.com/docs/v1.2/api/events/backend/form/extendFieldsBefore

**Comment by jlongo** [comment]
Thanks for your time Luke. I will give it a try.
JL

**Comment by jlongo** [comment]
I've changed the nested plugin [GinoPane.BlogTaxonomy](https://packagist.org/packages/ginopane/wn-blogtaxonomy-plugin) on Plugin.php line 277
```php

            // form->addSecondaryTabFields([
            $form->addTabFields([
                'categories' => $categoriesConfig,
                'tags' => [
```
And that merget the taxonomy menu on post blog main menu
Not a ideal solution, but working for now

TIA 

JL
