### ISSUE TITLE
Page Slug can be Zero and Negative

### ISSUE THREAD

**Issue by michaelheider** [wintercms/wn-blog-plugin#47]
### Overview

Negative and 0 page slugs are accepted. So, `blog/-3` is a valid URL and stays that way. Instead it should automatically become `blog/1`

### Actual Behaviour

Page 1 is displayed. But the URL is not changed to page 1. Instead it remains at 0 or a negative number.

### Expected Behaviour

Redirect to page 1.

### Other

With page slugs larger than the last page it correctly displayed the last page _and_ updates the URL to match.

When using a string as page slug, it automatically redirects to page 1, too.

### Workaround

Use this `onStart()` function:

```php
public function onStart() {
	if ((int)$this->param('page') < 1) {
		return redirect('/blog/1', 301);
	}
}
```

**Comment by bennothommo** [comment]
Thanks for the report.

This is certainly something we can look into, but there's readily available solutions now, including your own suggestion. The other would be to simply not show a "previous page" link on page 1, or show a page number below 1 in a list of page numbers when designing your templates.

**Comment by LukeTowers** [comment]
Fixed, thanks for the report!
