### ISSUE TITLE
Post.user.login don't seem to work anymore 

### ISSUE THREAD

**Issue by HitArrowLegend** [wintercms/wn-blog-plugin#6]
While looking at a post, I noticed that {{ post.user.login }} don't work anymore while it does on the rainlab version.

The same goes for post.user.first_name, last_name, email etc... 

The dump(post) also looks different (left is Winter)
![e1599ae1bb](https://user-images.githubusercontent.com/2132234/115948666-b06c3880-a4cf-11eb-9e73-1658a63f4557.png)

**Comment by RomainMazB** [comment]
ping @HitArrowLegend did you solved this?

I've just tested with oc-vanilla-theme in `Posts` and `Post` component and everything worked.

The only doubt I had is that when you first install the Blog plugin, [the `First blog post` article has no `user_id`](https://github.com/wintercms/wn-blog-plugin/blob/main/updates/v1.0.1/seed_all_tables.php#L17-L30) so I had to go to the backend to set one and re-save the post to attach it to the `User` model.

This may be the source of the incomprehension?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
