### ISSUE TITLE
Add the ability to add snippets as in the module pages

### ISSUE THREAD

**Issue by oim37** [wintercms/wn-blog-plugin#65]
Sometimes i want to add a gallery or some code to blog article, this is easily done in the pages module using snippets, I really want to be able to add snippets in this module too.

For example, i want to add a gallery to a blog article, i can, but need to go into the template and use a selection from the link, which is not very convenient.

```
if(strpos($_SERVER['REQUEST_URI'], '/news/my-article') !== false){
$this['newsurl']=true;
}

{% if newsurl == true %}
    {% partial 'second/my-article' %}
{% endif %}
```

While in the pages module this is done in the admin panel, by moving the mouse.

**Comment by LukeTowers** [comment]
@oim37 see https://github.com/wintercms/wn-pages-plugin/pull/36, feel free to test that out and see if you can get it across the finish line, or if you're interested in sponsoring finishing that feature feel free to reach out to me.

**Comment by oim37** [comment]
Super, thank you!
